# Generated by Django 4.1.7 on 2023-02-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='last_name',
            new_name='surname',
        ),
    ]
