# Generated by Django 4.1.7 on 2023-02-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_last_name_students_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.courses'),
        ),
    ]
